### ISSUE TITLE
Could we please have versioning?

### ISSUE THREAD

**Issue by patkai** [Insightly/php#16]
It seems that version 0.1 in the composer file doesn't change, even if there were many contributions merged. I would need versions when I include these files as a library. I suppose you are the only one who can bump the version, or is there any other sensible workflow? Many thanks!

**Comment by brianinsightly** [comment]
Thanks for the suggestion. I'll look into this. Thanks!

Brian

**Comment by davisn** [comment]
FYI, I just bumped the version identifier to composer.json with the latest change.  I'll try to do that consistently from now on.

**Comment by patkai** [comment]
Thank you!
